- name: installing nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest



  - name: removing default cantant website
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: absent

 ntend zip code
    ansible.builtin.unarchive:
      src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: copy the backend conf - name: create contant directory
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: directory

  - name: download and extract fro
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf

  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
    # notify:
    # - restart nginx



